# Generated by Django 5.1.3 on 2024-11-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_investorprofile'),
        ('investment', '0003_alter_inventment_user_alter_ledger_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='inventment',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_investments', to='account.investorprofile'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='investor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ledger', to='account.investorprofile'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='investor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_wallet', to='account.investorprofile'),
        ),
    ]
