# Generated by Django 5.1.3 on 2024-11-29 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_investorprofile'),
        ('investment', '0004_remove_inventment_user_remove_ledger_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ledger', to='account.investorprofile'),
        ),
    ]
