# Generated by Django 5.1.3 on 2024-11-30 01:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_alter_ledger_investor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='inventment',
            old_name='amount',
            new_name='deposit',
        ),
        migrations.AddField(
            model_name='inventment',
            name='revenue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
