# Generated by Django 5.1.3 on 2024-11-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_investorprofile'),
        ('investment', '0006_alter_ledger_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventment',
            new_name='Investment',
        ),
    ]
