# Generated by Django 5.1.3 on 2024-12-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_rename_inventment_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
